ci(.github): update helm-chart-smoketest with more k8s variations
spinframework/runtime-class-manager pull request #265
Opened 2024-11-15 18:35 UTC by vdice

## Describe your changes

- Updates the helm install smoke test with more k8s flavors!  Here we add minikube, microk8s and k3d
- Since they run in parallel, I figured running all cases both on PRs and merges to main is fine for now -- thoughts?

These distros all had GH actions ready-to-use.  For other distros we'd like to cover under test (k0s, etc), we could either craft a reusable action in-house and stick to the same matrix-based approach added here... or maybe break out into separate workflows.

- [x] Depends on https://github.com/spinkube/runtime-class-manager/pull/264 (microk8s specifically)
  - (See [successful runs on fork](https://github.com/vdice/runtime-class-manager/actions/runs/11861100389) which incorporates PR#264 alongside this commit)

## Issue ticket number and link

Ref https://github.com/spinkube/runtime-class-manager/issues/48

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- I tested the changes with the following distributions:
  - [x] Kind
  - [x] MiniKube
  - [x] MicroK8s
  - [x] K3s
  - [ ] Rancher RKE2
  - [ ] Azure AKS
  - [ ] GCP GKE (Ubuntu nodes)
  - [ ] AWS EKS (AmazonLinux2 nodes)
  - [ ] AWS EKS (Ubuntu nodes)
  - [ ] Digital Ocean Kubernetes

2025-03-16 21:54 UTC, voigt requested changes
Looking forward to merge this after #264 is merged!

2025-03-16 21:54 UTC, voigt commented on .github/workflows/helm-chart-smoketest.yml
> +  SHIM_SPIN_VERSION: v0.17.0
Lets update those versions
```suggestion
  K8S_VERSION: v1.32.2
  MICROK8S_CHANNEL: 1.32/stable
  SHIM_SPIN_VERSION: v0.18.0
```

2025-03-16 21:54 UTC, voigt commented on .github/workflows/helm-chart-smoketest.yml
> +      - name: Build ${{ matrix.config.name }}
Love the matrix approach!

2025-03-16 21:54 UTC, voigt commented on .github/workflows/helm-chart-smoketest.yml
> +        uses: actions/upload-artifact@v4
```suggestion
        uses: actions/upload-artifact@v6
```

2025-03-16 21:54 UTC, voigt commented on .github/workflows/helm-chart-smoketest.yml
> +          version: v3.15.4
```suggestion
          version: v3.17.2
```

2025-03-16 21:54 UTC, voigt commented on .github/workflows/helm-chart-smoketest.yml
> +        uses: medyagh/setup-minikube@v0.0.18
```suggestion
        uses: medyagh/setup-minikube@v0.0.19
```

2025-03-17 21:02 UTC, voigt commented
> Weird, currently getting the following from the shim-downloader just from the k3d cluster:
> 
> ```
> 2025-03-17T18:02:12	INFO	start downloading shim from  https://github.com/spinframework/containerd-shim-spin/releases/download/v0.18.0/containerd-shim-spin-v2-linux-x86_64.tar.gz...
> gzip: invalid magic
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> ```
> 
> Trying to figure out the underlying cause...

Feels like the downloaded file got corrupted... Maybe it would be a good idea to add a bit more verbose info to the downloader script...

Some ideas:

* removing the `-s` from curl to get filesize
* adding an `ls -lah` to check filesize
* print md5sum

Generally, printing curl and tar version wouldn't hurt either...

2025-03-19 20:42 UTC, vdice commented
I added some debug lines; oddly, I'm seeing variable behavior.  (Still only occuring for k3d; the other clusters all succeed.) Sometimes the shim is downloaded just fine and the provisioner proceeds with installation, other times the last log line seen is 'INFO	start downloading shim from ...' and the provisioner container is still pending, almost like the download is hanging.

Going to try to repro with a k3d cluster locally and see what I can find...

2025-04-16 21:27 UTC, vdice commented
@voigt ok, ready for a re-review. The issue with k3d was due to https://github.com/spinframework/runtime-class-manager/issues/371; I've pinned the [k8s version to 1.32.1](https://github.com/spinframework/runtime-class-manager/pull/265/files#diff-d3487c507ce515918635cd6b522af756b7eba7b596016bd621f2079860a05e58R7-R10) for the time being.

Do we want any or all of the debug info added to the download_shim.sh script?

2025-04-16 21:58 UTC, voigt commented
Uh! That was a nasty one. Great that you'll join figured it out!

IMO we should keep the debug info.

2025-04-16 21:58 UTC, voigt approved these changes

2025-04-16 22:06 UTC, merged